### ISSUE TITLE
AggregationException out of the box

### ISSUE THREAD

**Issue by SirEel** [eulerfx/DDDInventoryItemFSharp#2]
Steps: Get current code, build and run with no alteration. After about a 1-minute delay, System.AggregationException thrown in InventoryItemsController line 32. I made no changes to code or any project settings. Are there additional prerequisites to running the app?

**Comment by eulerfx** [comment]
Did you start the event store instance? What was the message in the exception?

**Comment by SirEel** [comment]
I am totally new to EventStore.

Your instructions say:
1.    Run EventStore.SingleNode.exe --run-projections
   -- Did that.  
2. Enable the $by_category projection.
   -- Don't know how to do that.  
3. Create new projections FlatReadModelProjection.js and OverviewReadModelProjection.js with mode=**Continuous** and Emit enabled.
   -- Don't know how to do that.

As result all the unit tests pass except initProjections(), which throws AggregationException on the third line. 

Result Message:
System.IO.IOException : Unable to read data from the transport connection: The connection was closed.

Result StackTrace:  
at System.Net.ConnectStream.InternalWrite(Boolean async, Byte[] buffer, Int32 offset, Int32 size, AsyncCallback callback, Object state)
   at System.Net.ConnectStream.BeginWrite(Byte[] buffer, Int32 offset, Int32 size, AsyncCallback callback, Object state)
   at EventStore.ClientAPI.Transport.Http.AsyncStreamCopier`1.InputReadCompleted(IAsyncResult ar)

**Comment by achomoko** [comment]
I had the same problem. I spent a few hours and worked out how to do steps 2 & 3 but could not get all tests to pass.

**Comment by M0ns1gn0r** [comment]
Yes, the provided instructions are too scarce. I haven't managed to run the tests either.
